ANSI_QUOTES aren't supported by default
Causing migration error like:
MySQLdb.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'"registration_registrationprofile"\' at line 1')